import { UIProvider } from "@repo/ui";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};
export default function RootLayout(props: { children: React.ReactNode }) {
	const { children } = props;
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<UIProvider>{children}</UIProvider>
			</body>
		</html>
	);
}
